### ISSUE TITLE
collection new

### ISSUE THREAD

**Issue by AntonTymczenko** [chingu-voyage4/Bears-Team-15#74]
at a blank new page

when I don't fill first (empty) card

I still can click on "add new card" button

**Comment by svmi3195** [comment]
I looked a bit into this. The console (with vue tools) shows that `newCollection` object in it's `items` has one empty object. This means, that then no check for `q` or `a` properties can run. Funny, but if I start filling the form mentioned properties do appear.
So, this kind of gets fixed if instead of 
`newCollection: {`
`      collectionName: '',`
`      items: [{...this.emptyCard}]`
`    },  `
I just use simple
`newCollection: {`
`      collectionName: '',`
 `     items: [{ q: '', a: '' }]`
 `   },  `
but I am not sure if this is a good fix.

**Comment by AntonTymczenko** [comment]
yeah, it was a bad idea to put some self-dependencies inside of `data`. There shouldn't be any `this. ... `
